--- #installation et configuration apache
- hosts:  localhost
  become:  yes
  tasks:
    - name:   Install apache
      yum:
        name:   httpd
        state:    latest
        name:    /srv/httpd.j2
        state:    touch   
    - name:   apache config file 
      template:
        src:    /srv/httpd.j2
        dest:   /etc/httpd/conf/httpd.conf
      notify:
      - restart apache
    - name: change port
      lineinfile:
        path:  /etc/httpd/conf/httpd.conf
        regexp:   '^Listen ' 
        insertafter:    '^#Listen '     
        line:   Listen 9000
    - name:   check apache is running
      service:
        name:   httpd
        state:    started
  # handlers:
  #   - name:   restart apache
  #     service:
  #       name:   httpd
  #       state:    restarted