--- #installation et configuration apache
- hosts:  localhost
  become:  yes
  vars:
    http_port:  81
  tasks:
    - name:   Install apache
      yum:
        name:   httpd
        state:    latest
    - name:   apache config file 
      template:
        src:    /srv/httpd.j2
        dest:   /etc/httpd/conf/httpd.conf
      notify:
      - restart apache
    - name:   check apache is running
      service:
        name:   httpd
        state:    started
  handlers:
    - name:   restart apache
      service:
        name:   httpd
        state:    restarted