---
# tasks file for JENKINS
- name: Install openJDK8
  yum:
    name: java-1.8.0-openjdk
    state: latest
- name: grab rpm key
  rpm_key:
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
  notify:
  - restart jenkins
